version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../develop:/var/www/html
      - ../apache2config/apache2/sites-available:/etc/apache2/sites-available
    ports:
      - 80:80