version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../:/var/www/html
    ports:
      - 80:80
  db:
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
    #volumes:
    #  - ../db_data:/var/lib/mysql